name: "Build linux image"

on:
  push:
    branches: [ main ]
    paths:
      - 'leap-linux/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'leap-linux/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  nix-build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Disable app armor. Causes problems with bwrap and Nix.
      run: |
        sudo aa-teardown || true
        sudo systemctl disable --now apparmor.service || true
        sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
    - uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix build .#leap-linux
    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
      with:
        name: leap-linux.img
        path: ./result/images/sdcard.img
